# Site settings
baseurl = "https://blog.loganwedwards.com/"
languageCode = "en-us"
title = "Logan Edwards"
theme = "hugo-cactus-theme"

[params]
	name = "Logan Edwards"
	description = "Occassional updates on my interests"
	bio = "Engineer and Maker (time permitting)"
	# Enter optionally your twitter account
	twitter = "loganwedwards"
	# Disable comments by leaving disqusShortname empty
	enableRSS = true
	RSSLink = "/index.xml"
	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Tracking
	googleAnalytics = "UA-77124828-1"

	# Navigation links
	home = "Home"
	about = "About"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Logan has a rich history in engineering beginning with the Lego obsession as a youngling. He went to school for mechanical engineering and found a love for design and mechatronics. He later discovered that software development provided a rapid means to delivering a product and is continuing his passion for meshing his atom and bit curiousities. Logan currently spends his time between Fount, his family and continuously learning."
	tweet = ""
	share = ""
	# 404 page
	title404 = "You can go about your business"
	subtitle404 = "Move along, move along."

[permalinks]
	post = "/:year/:month/:title"
