# Site settings
baseurl = "http://replace-this-with-your-domain.com/"
languageCode = "en-us"
title = "Hugo Cactus Theme"
theme = "hugo-cactus-theme"

[params]
	name = "Logan Edwards"
	description = "Describe your website"
	bio = "Digerati"
	# Enter optionally your twitter account
	twitter = "https://twitter.com/loganwedwards"
	# Disable comments by leaving disqusShortname empty
	disqusShortname = ""
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an engineer, family man and co-founder of Fount."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""
